server:
  port: 4500
jasypt:
  encryptor:
    #该密钥只用来生成密文使用，打包时要删掉，否则容易被别人看到密钥来破解密文
    password: dazhou
spring:
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://dz-community-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://dz-community-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: subject
          uri: lb://dz-community-subject
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0




