server:
  port: 4500
jasypt:
  encryptor:
    #该密钥只用来生成密文使用，打包时要删掉，否则容易被别人看到密钥来破解密文
    password: dazhou
spring:
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://dz-community-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://dz-community-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: subject
          uri: lb://dz-community-subject
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1





